### ISSUE TITLE
Make known_hosts optional

### ISSUE THREAD

**Issue by round-corgi** [shimataro/ssh-key-action#223]
Our use case is pretty simple - add a GitHub SSH key so we can push to GitHub without using a token.  GitHub known_hosts ssh key is already added by default, so we don't need to add one ourselves.

Would be nice to make this field optional.

**Comment by shimataro** [comment]
You can use `known_hosts: unnecessary`.

`known_hosts` is not optional.
It's designed intentionally because It should not be omitted casually (as you know, it is insecure to connect except `github.com` without `known_hosts`).

If you connect only to `github.com`, use `known_hosts: unnecessary` explicitly.

closing.

**Comment by nicolas-albert** [comment]
You should include this case in your main page : https://github.com/marketplace/actions/install-ssh-key

I found `known_hosts: unnecessary` just here with luck !
Also put this as a default value isn't a bad idea !

Thanks for your plugin.
